name: Build Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4.5.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v5.1.0
        with:
            python-version: ${{ matrix.python-version }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@465b7d8e732ca3921382b1674c59bada9cbf3399 #v2
        with:
          pandoc-version: '3.1.11' # The pandoc version to download (if necessary) and use.

      - name: Test pandoc
        run: echo "# Test" | pandoc -t html

        # See https://docs.github.com/en/actions/tutorials/build-and-test-code/python
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install ipython
            python -m pip install -r requirements.txt

      - name: Build documentation using Hatch
        run: |
            hatch run docs:build
